import re
import json

# Extra keys dictionary for the existing 14 languages:
EXTRA_KEYS = {
    'en': {
        'simulate': 'Simulate',
        'offline': 'Offline',
        'holdAction': 'HOLD',
        'sellNowAction': 'SELL NOW',
        'joinPoolAction': 'JOIN POOL',
        'factorPriceTrend': 'Price Trend',
        'factorWeather': 'Weather Forecast',
        'factorStorage': 'Storage Viability',
        'factorSpoilage': 'Spoilage Risk',
        'modifyLot': 'Modify Lot Parameters',
        'digitalLedger': 'Farmer Digital Ledger',
        'directSettlements': 'Direct Bank Settlements',
        'totalRealized': 'Total Realized Cash',
        'settledVolume': 'Settled Volume',
        'settledInvoices': 'Settled Invoices',
        'recordNewSale': 'Record New Sale',
    },
    'hi': {
        'simulate': 'सिम्युलेट',
        'offline': 'ऑफलाइन',
        'holdAction': 'रुकें',
        'sellNowAction': 'अभी बेचें',
        'joinPoolAction': 'पूल में शामिल हों',
        'factorPriceTrend': 'भाव का रुझान',
        'factorWeather': 'मौसम पूर्वानुमान',
        'factorStorage': 'भंडारण स्थिति',
        'factorSpoilage': 'खराब होने का जोखिम',
        'modifyLot': 'फसल विवरण बदलें',
        'digitalLedger': 'किसान डिजिटल बहीखाता',
        'directSettlements': 'सीधे बैंक खाते में भुगतान',
        'totalRealized': 'कुल प्राप्त नकद',
        'settledVolume': 'निपटाई गई मात्रा',
        'settledInvoices': 'भुगतान किए गए बिल',
        'recordNewSale': 'नई बिक्री दर्ज करें',
    },
    'mr': {
        'simulate': 'सिम्युलेट',
        'offline': 'ऑफलाइन',
        'holdAction': 'थांबा',
        'sellNowAction': 'आजच विका',
        'joinPoolAction': 'पूलमध्ये सामील व्हा',
        'factorPriceTrend': 'भावाचा कल',
        'factorWeather': 'हवामान अंदाज',
        'factorStorage': 'साठवणूक क्षमता',
        'factorSpoilage': 'नासाडीचा धोका',
        'modifyLot': 'शेतमालाचे तपशील बदला',
        'digitalLedger': 'शेतकरी डिजिटल खतावणी',
        'directSettlements': 'थेट बँक खात्यात जमा',
        'totalRealized': 'एकूण मिळालेली रोख',
        'settledVolume': 'विकलेली एकूण आवक',
        'settledInvoices': 'जमा झालेल्या पावत्या',
        'recordNewSale': 'नवीन विक्री नोंदवा',
    },
    'te': {
        'simulate': 'సిమ్యులేట్',
        'offline': 'ఆఫ్‌లైన్',
        'holdAction': 'ఆగండి',
        'sellNowAction': 'ఇప్పుడే అమ్మండి',
        'joinPoolAction': 'పూల్‌లో చేరండి',
        'factorPriceTrend': 'ధర సరళి',
        'factorWeather': 'వాతావరణ సూచన',
        'factorStorage': 'నిల్వ సామర్థ్యం',
        'factorSpoilage': 'పాడయ్యే ప్రమాదం',
        'modifyLot': 'పంట వివరాలను మార్చండి',
        'digitalLedger': 'రైతు డిజిటల్ లెడ్జర్',
        'directSettlements': 'నేరుగా బ్యాంక్ ఖాతాలో జమ',
        'totalRealized': 'మొత్తం చేతికి వచ్చిన నగదు',
        'settledVolume': 'విక్రయించిన పరిమాణం',
        'settledInvoices': 'చెల్లించిన రసీదులు',
        'recordNewSale': 'కొత్త అమ్మకాన్ని నమోదు చేయండి',
    },
    'ta': {
        'simulate': 'சிமுலேட்',
        'offline': 'ஆஃப்லைன்',
        'holdAction': 'காத்திருக்கவும்',
        'sellNowAction': 'இப்போதே விற்கவும்',
        'joinPoolAction': 'குழுவில் இணையுங்கள்',
        'factorPriceTrend': 'விலை போக்கு',
        'factorWeather': 'வானிலை முன்னறிவிப்பு',
        'factorStorage': 'சேமிப்பு வசதி',
        'factorSpoilage': 'சேதமடையும் ஆபத்து',
        'modifyLot': 'பயிர் விவரங்களை மாற்றவும்',
        'digitalLedger': 'விவசாயி டிஜிட்டல் கணக்கு',
        'directSettlements': 'நேரடி வங்கி பரிவர்த்தனை',
        'totalRealized': 'மொத்த ரொக்க வருவாய்',
        'settledVolume': 'விற்பனை அளவு',
        'settledInvoices': 'செட்டில் செய்யப்பட்ட ரசீதுகள்',
        'recordNewSale': 'புதிய விற்பனையை பதிவு செய்க',
    },
    'bn': {
        'simulate': 'অনুকরণ',
        'offline': 'অফলাইন',
        'holdAction': 'অপেক্ষা করুন',
        'sellNowAction': 'এখনই বিক্রি করুন',
        'joinPoolAction': 'পুলে যোগ দিন',
        'factorPriceTrend': 'দরের প্রবণতা',
        'factorWeather': 'আবহাওয়া পূর্বাভাস',
        'factorStorage': 'সংরক্ষণ ক্ষমতা',
        'factorSpoilage': 'নষ্ট হওয়ার ঝুঁকি',
        'modifyLot': 'ফসলের বিবরণ পরিবর্তন করুন',
        'digitalLedger': 'কৃষক ডিজিটাল খাতা',
        'directSettlements': 'সরাসরি ব্যাংক অ্যাকাউন্টে জমা',
        'totalRealized': 'মোট অর্জিত নগদ',
        'settledVolume': 'মোট বিক্রিত ফসল',
        'settledInvoices': 'পরিশোধিত চালান',
        'recordNewSale': 'নতুন বিক্রি যোগ করুন',
    },
    'gu': {
        'simulate': 'સિમ્યુલેટ',
        'offline': 'ઑફલાઇન',
        'holdAction': 'રાહ જુઓ',
        'sellNowAction': 'હમણાં જ વેચો',
        'joinPoolAction': 'પૂલમાં જોડાઓ',
        'factorPriceTrend': 'ભાવનું વલણ',
        'factorWeather': 'હવામાન આગાહી',
        'factorStorage': 'સંગ્રહ ક્ષમતા',
        'factorSpoilage': 'બગડવાનું જોખમ',
        'modifyLot': 'પાકની વિગતો બદલો',
        'digitalLedger': 'ખેડૂત ડિજિટલ ખાતાવહી',
        'directSettlements': 'સીધા બેંક ખાતામાં જમા',
        'totalRealized': 'કુલ મળેલી રોકડ',
        'settledVolume': 'વેચાયેલો જથ્થો',
        'settledInvoices': 'ચૂકવેલા બિલ',
        'recordNewSale': 'નવી વેચાણ નોંધણી',
    },
    'kn': {
        'simulate': 'ಸಿಮ್ಯುಲೇಟ್',
        'offline': 'ಆಫ್‌ಲೈನ್',
        'holdAction': 'ಕಾಯಿರಿ',
        'sellNowAction': 'ಈಗಲೇ ಮಾರಿ',
        'joinPoolAction': 'ಪೂಲ್ ಸೇರಿ',
        'factorPriceTrend': 'ಬೆಲೆ ಪ್ರವೃತ್ತಿ',
        'factorWeather': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
        'factorStorage': 'ಶೇಖರಣಾ ಸಾಮರ್ಥ್ಯ',
        'factorSpoilage': 'ಹಾಳಾಗುವ ಅಪಾಯ',
        'modifyLot': 'ಬೆಳೆ ವಿವರಗಳನ್ನು ಬದಲಾಯಿಸಿ',
        'digitalLedger': 'ರೈತರ ಡಿಜಿಟಲ್ ಲೆಡ್ಜರ್',
        'directSettlements': 'ನೇರ ಬ್ಯಾಂಕ್ ಜಮೆ',
        'totalRealized': 'ಒಟ್ಟು ಕೈಸೇರಿದ ನಗದು',
        'settledVolume': 'ಮಾರಾಟವಾದ ಒಟ್ಟು ಪ್ರಮಾಣ',
        'settledInvoices': 'ಪಾವತಿಯಾದ ರಶೀದಿಗಳು',
        'recordNewSale': 'ಹೊಸ ಮಾರಾಟ ದಾಖಲಿಸಿ',
    },
    'ml': {
        'simulate': 'സിമുലേറ്റ്',
        'offline': 'ഓഫ്‌ലൈൻ',
        'holdAction': 'കാത്തിരിക്കുക',
        'sellNowAction': 'ഇപ്പോൾ വിൽക്കുക',
        'joinPoolAction': 'പൂളിൽ ചേരുക',
        'factorPriceTrend': 'വില പ്രവണത',
        'factorWeather': 'കാലാവസ്ഥ പ്രവചനം',
        'factorStorage': 'സംഭരണ സൗകര്യം',
        'factorSpoilage': 'കേടാകാനുള്ള സാധ്യത',
        'modifyLot': 'വിള വിവരങ്ങൾ മാറ്റുക',
        'digitalLedger': 'കർഷക ഡിജിറ്റൽ ലെഡ്ജർ',
        'directSettlements': 'നേരിട്ട് ബാങ്ക് അക്കൗണ്ടിലേക്ക്',
        'totalRealized': 'ആകെ ലഭിച്ച പണം',
        'settledVolume': 'വിറ്റുവരവ് അളവ്',
        'settledInvoices': 'തീർപ്പാക്കിയ ബില്ലുകൾ',
        'recordNewSale': 'പുതിയ വിൽപ്പന രേഖപ്പെടുത്തുക',
    },
    'pa': {
        'simulate': 'ਸਿਮੂਲੇਟ',
        'offline': 'ਔਫਲਾਈਨ',
        'holdAction': 'ਉਡੀਕੋ',
        'sellNowAction': 'ਹੁਣੇ ਵੇਚੋ',
        'joinPoolAction': 'ਪੂਲ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
        'factorPriceTrend': 'ਭਾਅ ਦਾ ਰੁਝਾਨ',
        'factorWeather': 'ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ',
        'factorStorage': 'ਸਟੋਰੇਜ ਸਮਰੱਥਾ',
        'factorSpoilage': 'ਖ਼ਰਾਬ ਹੋਣ ਦਾ ਖ਼ਤਰਾ',
        'modifyLot': 'ਫ਼ਸਲ ਦੇ ਵੇਰਵੇ ਬਦਲੋ',
        'digitalLedger': 'ਕਿਸਾਨ ਡਿਜੀਟਲ ਖਾਤਾ',
        'directSettlements': 'ਸਿੱਧੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਭੁਗਤਾਨ',
        'totalRealized': 'ਕੁੱਲ ਮਿਲੀ ਨਕਦੀ',
        'settledVolume': 'ਨਿਪਟਾਈ ਗਈ ਮਾਤਰਾ',
        'settledInvoices': 'ਭੁਗਤਾਨ ਕੀਤੇ ਬਿੱਲ',
        'recordNewSale': 'ਨਵੀਂ ਵਿਕਰੀ ਦਰਜ ਕਰੋ',
    },
    'or': {
        'simulate': 'ଅନୁକରଣ',
        'offline': 'ଅଫଲାଇନ୍',
        'holdAction': 'ଅପେକ୍ଷା କରନ୍ତୁ',
        'sellNowAction': 'ଏବେ ବିକ୍ରି କରନ୍ତୁ',
        'joinPoolAction': 'ପୁଲ୍‌ରେ ସାମିଲ ହୁଅନ୍ତୁ',
        'factorPriceTrend': 'ଦର ପ୍ରବୃତ୍ତି',
        'factorWeather': 'ପାଣିପାଗ ପୂର୍ବାନୁମାନ',
        'factorStorage': 'ଭଣ୍ଡାରଣ ସୁବିଧା',
        'factorSpoilage': 'ନଷ୍ଟ ହେବାର ଆଶଙ୍କା',
        'modifyLot': 'ଫସଲ ବିବରଣୀ ବଦଳାନ୍ତୁ',
        'digitalLedger': 'କୃଷକ ଡିଜିଟାଲ୍ ଖାତା',
        'directSettlements': 'ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଜମା',
        'totalRealized': 'ମୋଟ ପ୍ରାପ୍ତ ନଗଦ',
        'settledVolume': 'ବିକ୍ରି ହୋଇଥିବା ପରିମାଣ',
        'settledInvoices': 'ପରିଶୋଧିତ ରସିଦ',
        'recordNewSale': 'ନୂତନ ବିକ୍ରି ପଞ୍ଜୀକରଣ',
    },
    'as': {
        'simulate': 'অনুকৰণ',
        'offline': 'অফলাইন',
        'holdAction': 'অপেক্ষা কৰক',
        'sellNowAction': 'এতিয়াই বিক্ৰী কৰক',
        'joinPoolAction': 'পুলত যোগ দিয়ক',
        'factorPriceTrend': 'দৰৰ ধাৰা',
        'factorWeather': 'বতৰৰ পূৰ্বাভাস',
        'factorStorage': 'সংৰক্ষণ ক্ষমতা',
        'factorSpoilage': 'নষ্ট হোৱাৰ আশংকা',
        'modifyLot': 'শস্যৰ বিৱৰণ সলনি কৰক',
        'digitalLedger': 'কৃষক ডিজিটেল খাতা',
        'directSettlements': 'পোনপটীয়াকৈ বেংক একাউণ্টত জমা',
        'totalRealized': 'মুঠ পোৱা নগদ',
        'settledVolume': 'বিক্ৰী হোৱা পৰিমাণ',
        'settledInvoices': 'পৰিশোধিত বিল',
        'recordNewSale': 'নতুন বিক্ৰী পঞ্জীয়ন কৰক',
    },
    'ur': {
        'simulate': 'مشق',
        'offline': 'آف لائن',
        'holdAction': 'انتظار کریں',
        'sellNowAction': 'ابھی بیچیں',
        'joinPoolAction': 'پول میں شامل ہوں',
        'factorPriceTrend': 'قیمت کا رجحان',
        'factorWeather': 'موسم کی پیش گوئی',
        'factorStorage': 'ذخیرہ اندوزی کی صلاحیت',
        'factorSpoilage': 'خراب ہونے کا خطرہ',
        'modifyLot': 'فصل کی تفصیلات تبدیل کریں',
        'digitalLedger': 'کسان ڈیجیٹل کھاتہ',
        'directSettlements': 'براہ راست بینک ادائیگی',
        'totalRealized': 'کل موصول شدہ نقد',
        'settledVolume': 'فروخت شدہ مقدار',
        'settledInvoices': 'ادا شدہ بل',
        'recordNewSale': 'نئی فروخت درج کریں',
    },
    'ne': {
        'simulate': 'सिम्युलेट',
        'offline': 'अफलाइन',
        'holdAction': 'कुर्नुहोस्',
        'sellNowAction': 'अहिले बेच्नुहोस्',
        'joinPoolAction': 'पूलमा सामेल हुनुहोस्',
        'factorPriceTrend': 'मूल्य प्रवृत्ति',
        'factorWeather': 'मौसम पूर्वानुमान',
        'factorStorage': 'भण्डारण क्षमता',
        'factorSpoilage': 'खराब हुने जोखिम',
        'modifyLot': 'बाली विवरण परिवर्तन गर्नुहोस्',
        'digitalLedger': 'किसान डिजिटल खाता',
        'directSettlements': 'सिधै बैंक खातामा भुक्तानी',
        'totalRealized': 'कुल प्राप्त नगद',
        'settledVolume': 'बिक्री भएको परिमाण',
        'settledInvoices': 'भुक्तानी भएका बिलहरू',
        'recordNewSale': 'नयाँ बिक्री दर्ता गर्नुहोस्',
    }
}

print("Loaded extra keys for 14 languages.")
