# Complete translations for the 9 scheduled languages that lacked full coverage
# Every single key is authentically translated into the native language & script.

NINE_LANGS = {
    'sa': {
        'appName': 'मण्डिमित्रम्',
        'subtitle': 'मण्डिनिर्णयकेन्द्रम्',
        'judgeDemo': 'परीक्षकप्रदर्शनम्',
        'easyMode': 'सरलविधिः',
        'simulate': 'अनुकुरु',
        'offline': 'जालमुक्तम्',
        'onlineStatus': 'संजालयुक्तम् (प्रातः ७:३० समकालिकम्)',
        'offlineStatus': 'संजालहीनम् (रक्षितम्)',
        'sihEvaluation': 'SIH परीक्षणविधिः',
        'testScenarios': 'कृषकपरिस्थितीः परीक्षताम्:',
        'scenario1': 'तिष्ठतु (पलाण्डुः)',
        'scenario2': 'अधुना विक्रयणम् (रक्ताङ्गकम्)',
        'scenario3': 'सामूहिकसमूहः',
        'greeting': 'सुप्रभातम्, रामेश्वर महोदय! 👋',
        'location': 'रामेश्वर महोदयः • निफाड, नासिक (महाराष्ट्रम्)',
        'geoVerified': 'भौगोलिकप्रमाणितम्',
        'onFarmStorage': 'क्षेत्रे सङ्ग्रहस्थानम्',
        'todaysMandi': 'अद्यतनी स्थानीयविपणिः',
        'sellingDecision': 'भवतः विक्रयनिर्णयः',
        'confidence': 'विश्वसनीयता',
        'sellTodayNet': 'अद्य विक्रयेण शुद्धप्राप्तिः',
        'spotPrice': 'प्रत्यक्षमूल्यम्',
        'mathDifferenceGain': 'अतिरिक्तलाभः',
        'whyThis': 'किमर्थम् अयम् निर्णयः? (कारणानि)',
        'compareMandis': 'विपणीनां तुलनां कुरुत',
        'whatIfTitle': 'प्रतीक्षां कुर्मः चेत् किम्? (अनुकारि)',
        'whatIfSubtitle': 'दिनानाम् आधारेण वास्तविकशुद्धप्राप्तिं पश्यतु',
        'testVariables': 'विभिन्नान् चरान् परीक्षताम्:',
        'storageToggle': 'सङ्ग्रहस्थानम्',
        'rainToggle': 'वृष्टिचेतावनी',
        'cashToggle': 'धनस्यावश्यकता',
        'decisionFormulaTitle': 'निर्णयबुद्धिमत्ता गणितसूत्रं च',
        'decisionFormulaSubtitle': 'SIH कलनविधिः',
        'whereToSell': 'कुत्र विक्रयणं करणीयम्? (उत्तमविपणिः)',
        'bestNetRealization': 'हस्ते लभ्यमानः श्रेष्ठशुद्धलाभः',
        'headlineWarning': '⚠️ फलकेषु दृश्यमानैः उच्चमूल्यैः भ्रान्ताः मा भवत। शुद्धादायं ज्ञातुं व्ययं न्यूनीकुरुत।',
        'leverageTitle': 'मूल्यनिर्धारणशक्तिः (लीवरेज)',
        'leverageSubtitle': 'व्यापारीभिः सह संभाषणात् पूर्वं स्वकीयां न्यूनतमसीमाम् अवगच्छतु',
        'mandiBenchmark': 'विपणिमानदण्डः',
        'fairFarmgateBand': 'उचितक्षेत्रमूल्यपरिधिः',
        'hardFloorWarning': 'अद्य अस्मात् न्यूनतमात् अधः मा विक्रीणीत',
        'shareWhatsApp', 'संवादपत्रे मूल्यपत्रं प्रेषयतु',
        'aggregatedSelling': 'सामूहिकविक्रयणम्',
        'popUpPoolTitle': 'सामूहिकसमूहः साक्षात् क्रेतारश्च',
        'bulkBonus': 'सामूहिकपारितोषिकम्',
        'poolProgress': 'समूहप्रगतिः',
        'joinPoolBtn': 'समूहे सम्मिलतु',
        'verifiedBuyers': 'प्रमाणितसाक्षात्क्रेतारः',
        'acceptOfferBtn': 'प्रस्तावं स्वीकुरु भारमापनं च आरक्षतु',
        'quickEntry': 'शीघ्रप्रविष्टिः',
        'speakToEnter': 'उक्त्वा सस्यं प्रविशतु',
        'recentDispatch': 'सद्यः समापितं प्रेषणम्',
        'dbtSettled': 'कोशे निक्षिप्तम् (DBT)',
        'disclaimerTitle': 'मण्डिमित्र निर्णयसहायकप्रणाली',
        'disclaimerText': 'परामर्शाः सर्वकारीयागमार्कनेट्-मौसमपूर्वानुमानयोः आधारिताः सन्ति।',
        'navHome': 'गृहम्',
        'navDecision': 'निर्णयः',
        'navMarkets': 'विपणयः',
        'navBuyers': 'क्रेतारः',
        'navLedger': 'गणनापत्रम्',
        'holdAction': 'तिष्ठतु',
        'sellNowAction': 'इदानीमेव विक्रयणम्',
        'joinPoolAction': 'समूहे सम्मिलतु',
        'factorPriceTrend': 'मूल्यप्रवृत्तिः',
        'factorWeather': 'ऋतुपूर्वानुमानम्',
        'factorStorage': 'सङ्ग्रहक्षमता',
        'factorSpoilage': 'विनाशभयम्',
        'modifyLot': 'सस्यविवरणं परिवर्तयतु',
        'digitalLedger': 'कृषकडिजिटलगणनापत्रम्',
        'directSettlements': 'साक्षात् कोशे जमा',
        'totalRealized': 'कुलप्राप्तधनम्',
        'settledVolume': 'विक्रीता परिमितिः',
        'settledInvoices': 'भुगतानपत्राणि',
        'recordNewSale': 'नूतनविक्रयं पञ्जीकुरुत'
    },
    'mai': {
        'appName': 'मंडीमित्र',
        'subtitle': 'मंडी निर्णय केंद्र',
        'judgeDemo': 'जज डेमो',
        'easyMode': 'सरल मोड',
        'simulate': 'सिम्युलेट',
        'offline': 'ऑफलाइन',
        'onlineStatus': 'ऑनलाइन (सवेरे ७:३० सिंक)',
        'offlineStatus': 'ऑफलाइन (रक्षित डेटा)',
        'sihEvaluation': 'SIH मूल्यांकन मोड',
        'testScenarios': 'किसान स्थिति देखू:',
        'scenario1': 'रुकू (पियाज)',
        'scenario2': 'एखने बेचू (टमाटर)',
        'scenario3': 'पॉप-अप पूल',
        'greeting': 'प्रणाम, रामेश्वर जी! 👋',
        'location': 'रामेश्वर जी • निफाड, नासिक (महाराष्ट्र)',
        'geoVerified': 'स्थान सत्यापित',
        'onFarmStorage': 'खेत पर भंडारण',
        'todaysMandi': 'आइुक स्थानीय मंडी भाव',
        'sellingDecision': 'अहाँक बेचय केर निर्णय',
        'confidence': 'विश्वास स्तर',
        'sellTodayNet': 'आइ बेचला पर शुद्ध नकद',
        'spotPrice': 'हाजिर भाव',
        'mathDifferenceGain': 'अतिरिक्त लाभ',
        'whyThis': 'ई निर्णय किएक? (कारण)',
        'compareMandis': 'मंडी सभक तुलना करू',
        'whatIfTitle': 'रुकला पर की होएत? (सिम्युलेटर)',
        'whatIfSubtitle': 'दिनक अनुसार अपन वास्तविक कमाई देखू',
        'testVariables': 'परिस्थिति बदलि कऽ देखू:',
        'storageToggle': 'भंडारण',
        'rainToggle': 'वर्षा चेतावनी',
        'cashToggle': 'पइसाक जरूरत',
        'decisionFormulaTitle': 'निर्णय बुद्धिमत्ता आ गणितीय सूत्र',
        'decisionFormulaSubtitle': 'SIH एल्गोरिदम विश्लेषण',
        'whereToSell': 'कतय बेची? (सबसँ निक मंडी)',
        'bestNetRealization': 'हाथ मे आबय वला सर्वश्रेष्ठ शुद्ध लाभ',
        'headlineWarning': '⚠️ पैघ भाव देखि कऽ धोखा नहि खाउ। ढुलाई घटा कऽ शुद्ध बचत देखू।',
        'leverageTitle': 'मोलभाव क्षमता (लीवरेज)',
        'leverageSubtitle': 'व्यापारी सं बात करबा सं पहिने अपन न्यूनतम भाव जानू',
        'mandiBenchmark': 'मंडी मानक भाव',
        'fairFarmgateBand': 'उचित खेत भाव दायरा',
        'hardFloorWarning': 'आइ ई न्यूनतम भाव सँ कम मे कखनो नहि बेचू',
        'shareWhatsApp': 'व्हाट्सएप पर भाव कार्ड भेजू',
        'aggregatedSelling': 'सामूहिक बिक्री (पूल)',
        'popUpPoolTitle': 'पॉप-अप पूल आ सीधा खरीदार',
        'bulkBonus': 'थोक बोनस',
        'poolProgress': 'पूल प्रगति',
        'joinPoolBtn': 'पूल मे शामिल होऊ',
        'verifiedBuyers': 'सत्यापित सीधा खरीदार',
        'acceptOfferBtn': 'प्रस्ताव स्वीकार कऽ वजन बुक करू',
        'quickEntry': 'झटपट प्रविष्टि',
        'speakToEnter': 'बोली कऽ फसल दर्ज करू',
        'recentDispatch': 'हालक भुक्तान',
        'dbtSettled': 'खाता मे जमा भेल (DBT)',
        'disclaimerTitle': 'मंडीमित्र निर्णय सहायता प्रणाली',
        'disclaimerText': 'सिफारिश सरकारी एगमार्कनेट आ मौसम पूर्वानुमान पर आधारित अछि।',
        'navHome': 'घर',
        'navDecision': 'निर्णय',
        'navMarkets': 'मंडी',
        'navBuyers': 'खरीदार',
        'navLedger': 'बहीखाता',
        'holdAction': 'रुकू',
        'sellNowAction': 'एखने बेचू',
        'joinPoolAction': 'पूल मे शामिल होऊ',
        'factorPriceTrend': 'भावक रुझान',
        'factorWeather': 'मौसम पूर्वानुमान',
        'factorStorage': 'भंडारण क्षमता',
        'factorSpoilage': 'खराब होमय के खतरा',
        'modifyLot': 'फसल विवरण बदलू',
        'digitalLedger': 'किसान डिजिटल बहीखाता',
        'directSettlements': 'सीधे बैंक खाता मे जमा',
        'totalRealized': 'कुल प्राप्त नकद',
        'settledVolume': 'बेचल गेल मात्रा',
        'settledInvoices': 'भुक्तान भेल बिल',
        'recordNewSale': 'नव बिक्री दर्ज करू'
    },
    'ks': {
        'appName': 'منڈی مِتر',
        'subtitle': 'منڈی فیصلہ مرکز',
        'judgeDemo': 'جج ڈیمو',
        'easyMode': 'آسان موڈ',
        'simulate': 'مشق',
        'offline': 'آف لائن',
        'onlineStatus': 'آن لائن (صبح ۷:۳۰)',
        'offlineStatus': 'آف لائن (محفوظ ڈیٹا)',
        'sihEvaluation': 'SIH تشخیصی موڈ',
        'testScenarios': 'کسان حالات وچھِو:',
        'scenario1': 'ترٲوِتھ تھاوِو (گنڈٕ)',
        'scenario2': 'وُنہٕ کٕنِو (ٹماٹر)',
        'scenario3': 'پوپ اپ پول',
        'greeting': 'سلام، رامیشور صاحب 👋',
        'location': 'رامیشور صاحب • نپھاڑ، ناسک (مہاراشٹرا)',
        'geoVerified': 'جغرافیائی تصدیق شدہ',
        'onFarmStorage': 'فارم اسٹوٗریج',
        'todaysMandi': 'ازُک مقامی منڈی ریٹ',
        'sellingDecision': 'تُہند کُننُک فٲصلہٕ',
        'confidence': 'اعتماد',
        'sellTodayNet': 'از کُننہٕ سٕتۍ اصلی کماے',
        'spotPrice': 'نقد قیمت',
        'mathDifferenceGain': 'اضافی منافعہٕ',
        'whyThis': 'یہ کِتھ پٲٹھ بنو؟ (وجہ)',
        'compareMandis': 'منڈین ہُنٛد موازنہٕ کٔرِو',
        'whatIfTitle': 'روٗزِتھ کیاہ گژھِ؟ (سمیولیٹر)',
        'whatIfSubtitle': 'دۄہن ہندِس حِسابہٕ اصلی کمائی وچھِو',
        'testVariables': 'حالات بدلاوِتھ پرکھِو:',
        'storageToggle': 'اسٹوٗریج',
        'rainToggle': 'روٗدُک خطرہٕ',
        'cashToggle': 'پونٛسن ہنٛز ضرورت',
        'decisionFormulaTitle': 'فٲصلہٕ فارمولا تہٕ حِساب',
        'decisionFormulaSubtitle': 'SIH الگورتھم تفصیٖل',
        'whereToSell': 'کتی کُناں؟ (بہترین منڈی)',
        'bestNetRealization': 'ہتھس منٛز ینہٕ وول بہترین منافعہٕ',
        'headlineWarning': '⚠️ زیادٕ ریٹ وچھِتھ دھوکہٕ مَہ کھیو۔ گاڑی کرایہٕ کٔڈِتھ خالص منافعہٕ وچھِو۔',
        'leverageTitle': 'سودا بازی طاقت',
        'leverageSubtitle': 'بیوپارین سٕتۍ کتھ کرنہٕ برونٛہہ پنُن کم از کم ریٹ زٲنِو',
        'mandiBenchmark': 'منڈی معیار',
        'fairFarmgateBand': 'مناسب کھیت ریٹ',
        'hardFloorWarning': 'از یَتھ ریٹہٕ کھۄتہٕ کم قِیمتس پؠٹھ مَہ کٕنِو',
        'shareWhatsApp': 'واٹس ایپ پؠٹھ ریٹ کارڈ سوزِو',
        'aggregatedSelling': 'شراکت داری کُنُن (پول)',
        'popUpPoolTitle': 'پاپ اپ پول تہٕ کھرے گاہک',
        'bulkBonus': 'بڑی تعداد ہُنٛد بونس',
        'poolProgress': 'پول ترقی',
        'joinPoolBtn': 'پولس منٛز شٲمل گژھِو',
        'verifiedBuyers': 'تصدیق شدہ گاہک',
        'acceptOfferBtn': 'پیشکش قبوٗل کٔرِتھ وزن بُک کٔرِو',
        'quickEntry': 'تیز اندراج',
        'speakToEnter': 'بٲلِتھ فصل درج کٔرِو',
        'recentDispatch': 'حالیہ روانگی',
        'dbtSettled': 'کھاتس منٛز جمع (DBT)',
        'disclaimerTitle': 'منڈی مِتر فٲصلہٕ سپورٹ سسٹم',
        'disclaimerText': 'یہِ فٲصلہٕ چھُ سرکاری ایگمارک نیٹ تہٕ موسمِک اندازس پؠٹھ مبنی۔',
        'navHome': 'گھر',
        'navDecision': 'فٲصلہٕ',
        'navMarkets': 'منڈی',
        'navBuyers': 'خریدار',
        'navLedger': 'کھاتہٕ',
        'holdAction': 'ترٲوِتھ تھاوِو',
        'sellNowAction': 'وُنہٕ کٕنِو',
        'joinPoolAction': 'پولس منٛز شٲمل گژھِو',
        'factorPriceTrend': 'قیمتُک رجحان',
        'factorWeather': 'موسمُک حال',
        'factorStorage': 'محفوظ تھاونٕچ سکت',
        'factorSpoilage': 'خراب گژھنُک خطرہ',
        'modifyLot': 'فصل تفصیٖل بدلاوِو',
        'digitalLedger': 'کسان ڈیجیٹل کھاتہٕ',
        'directSettlements': 'بینک کھاتس منٛز ادائیگی',
        'totalRealized': 'کُل ملٔمژ رقم',
        'settledVolume': 'کُنمُژ مقدار',
        'settledInvoices': 'ادا شُدٕ بِل',
        'recordNewSale': 'نوٚو کُنُن درج کٔرِو'
    },
    'gom': {
        'appName': 'मंडीमित्र',
        'subtitle': 'मंडी निर्णय केंद्र',
        'judgeDemo': 'जज डेमो',
        'easyMode': 'सोपें मोड',
        'simulate': 'सिम्युलेट',
        'offline': 'ऑफलाइन',
        'onlineStatus': 'ऑनलाइन (सकाळी ७:३० सिंक)',
        'offlineStatus': 'ऑफलाइन (सांठवलेला डेटा)',
        'sihEvaluation': 'SIH मूल्यांकन मोड',
        'testScenarios': 'शेतकरी परिस्थिती तपासात:',
        'scenario1': 'रावात (कांदो)',
        'scenario2': 'आताच विकात (टोमॅटो)',
        'scenario3': 'पॉप-अप पूल',
        'greeting': 'देव बरें करूं, रामेश्वर जी 👋',
        'location': 'रामेश्वर जी • निफाड, नाशिक (महाराष्ट्र)',
        'geoVerified': 'थळ निश्चित',
        'onFarmStorage': 'शेतांत साठवणूक',
        'todaysMandi': 'आयचो थळावो बाजार भाव',
        'sellingDecision': 'तुमचो विकपाचो निर्णय',
        'confidence': 'विश्वास',
        'sellTodayNet': 'आयज विकल्यार मेळपी रोख',
        'spotPrice': 'हजर भाव',
        'mathDifferenceGain': 'अदीक नफा',
        'whyThis': 'हो निर्णय कित्याक? (कारण)',
        'compareMandis': 'बाजारांची तुलना करात',
        'whatIfTitle': 'रावल्यार कितें जातलें? (सिम्युलेटर)',
        'whatIfSubtitle': 'दिसां प्रमाण तुमची खरी रोख पळयात',
        'testVariables': 'परिस्थिती बदलून पळयात:',
        'storageToggle': 'साठवणूक',
        'rainToggle': 'पावसाची शिटकावणी',
        'cashToggle': 'पैशांची गरज',
        'decisionFormulaTitle': 'निर्णय बुद्धिमत्ता आनी गणितीय सूत्र',
        'decisionFormulaSubtitle': 'SIH अल्गोरिदम फोडणी',
        'whereToSell': 'खंय विकचें? (उत्तम बाजार)',
        'bestNetRealization': 'हातांत मेळपी उत्कृश्ट नक्त नफा',
        'headlineWarning': '⚠️ व्हड दर पळवून फसू नाकात. येरादारी वजा करून हातात कितें उरता तें पळयात.',
        'leverageTitle': 'मोलभाव तांक (लीवरेज)',
        'leverageSubtitle': 'व्यापाऱ्या कडेन उलोवंचे पयलीं तुमचो उण्यांत उणो भाव जाणा जायात',
        'mandiBenchmark': 'बाजार प्रमाण',
        'fairFarmgateBand': 'योग्य शेत भाव मर्यादा',
        'hardFloorWarning': 'आयज ह्या उण्या दरा परस उण्या भावाक विकू नाकात',
        'shareWhatsApp': 'व्हॉट्सॲप चेर भाव कार्ड धाडात',
        'aggregatedSelling': 'एकवटून विक्री (पूल)',
        'popUpPoolTitle': 'पॉप-अप पूल आनी थेट खरेदीदार',
        'bulkBonus': 'मोठ्या प्रमाणाचेर बोनस',
        'poolProgress': 'पूल प्रगती',
        'joinPoolBtn': 'पूलान्त सामील जायात',
        'verifiedBuyers': 'खात्रीशीर थेट खरेदीदार',
        'acceptOfferBtn': 'ऑफर मानून घेयात आनी वजन बुक करात',
        'quickEntry': 'रोखडी नोंदणी',
        'speakToEnter': 'उलोवन पीक नोंद करात',
        'recentDispatch': 'हालींचो पावती जमा',
        'dbtSettled': 'खात्यांत जमा (DBT)',
        'disclaimerTitle': 'मंडीमित्र निर्णय मदत वेवस्था',
        'disclaimerText': 'शिफारशी सरकारी एगमार्कनेट आनी हवामान अंदाजाचेर आदारित आसात.',
        'navHome': 'घर',
        'navDecision': 'निर्णय',
        'navMarkets': 'बाजार',
        'navBuyers': 'खरेदीदार',
        'navLedger': 'हिशोब',
        'holdAction': 'रावात',
        'sellNowAction': 'आताच विकात',
        'joinPoolAction': 'पूलान्त सामील जायात',
        'factorPriceTrend': 'दराचो कल',
        'factorWeather': 'हवामानाचो अदमास',
        'factorStorage': 'सांठवणूक तांक',
        'factorSpoilage': 'नासाडीचो धोको',
        'modifyLot': 'मालाचे तपशील बदलात',
        'digitalLedger': 'शेतकरी डिजिटल खतावणी',
        'directSettlements': 'थेट बँक खात्यांत जमा',
        'totalRealized': 'एकूण मेळिल्ली रोख',
        'settledVolume': 'विकिल्ली एकूण आवक',
        'settledInvoices': 'जमा जाल्ल्यो पावत्यो',
        'recordNewSale': 'नवी विक्री नोंद करात'
    },
    'sd': {
        'appName': 'منڊي مِتر',
        'subtitle': 'منڊي فيصلو مرڪز',
        'judgeDemo': 'جج ڊيمو',
        'easyMode': 'سولو موڊ',
        'simulate': 'مشق',
        'offline': 'آف لائن',
        'onlineStatus': 'آن لائن (صبح ۷:۳۰)',
        'offlineStatus': 'آف لائن (محفوظ ڊيٽا)',
        'sihEvaluation': 'SIH تشخيص موڊ',
        'testScenarios': 'هارين جون حالتون ڏسو:',
        'scenario1': 'ترسو (بصر)',
        'scenario2': 'هاڻي وڪرو ڪريو (ٽماٽو)',
        'scenario3': 'پاپ اپ پول',
        'greeting': 'سلام، راميشور صاحب 👋',
        'location': 'راميشور صاحب • نفاڙ، ناسڪ (مهاراشٽر)',
        'geoVerified': 'مقام جي تصديق ٿيل',
        'onFarmStorage': 'ٻنيءَ تي گودام',
        'todaysMandi': 'اڄوڪو مقامي منڊي اگهه',
        'sellingDecision': 'اوهان جو وڪرو جو فيصلو',
        'confidence': 'اعتماد',
        'sellTodayNet': 'اڄ وڪڻڻ سان صاف ڪمائي',
        'spotPrice': 'روڪ اگهه',
        'mathDifferenceGain': 'اضافي منافعو',
        'whyThis': 'هي فيصلو ڇو؟ (سبب)',
        'compareMandis': 'منڊين جي ڀيٽ ڪريو',
        'whatIfTitle': 'جيڪڏهن ترسجي ته ڇا ٿيندو؟ (سميوليٽر)',
        'whatIfSubtitle': 'ڏينهن جي حساب سان پنهنجي اصل ڪمائي ڏسو',
        'testVariables': 'حالتون مٽائي ڏسو:',
        'storageToggle': 'گودام',
        'rainToggle': 'مينهن جو خطرو',
        'cashToggle': 'پئسن جي سخت ضرورت',
        'decisionFormulaTitle': 'فيصلو ڏاهپ ۽ حسابي فارمولا',
        'decisionFormulaSubtitle': 'SIH الگورٿم تفصيل',
        'whereToSell': 'ڪٿي وڪڻجي؟ (بهترين منڊي)',
        'bestNetRealization': 'هٿ ۾ ايندڙ بهترين خالص منافعو',
        'headlineWarning': '⚠️ وڏا اگهه ڏسي دوکو نه کائو. گاڏي ڀاڙو ڪٽي پنهنجو نفعو ڏسو.',
        'leverageTitle': 'سوديبازي جي طاقت (ليوريج)',
        'leverageSubtitle': 'واپارين سان ڳالهائڻ کان اڳ پنهنجو گهٽ ۾ گهٽ اگهه ڄاڻو',
        'mandiBenchmark': 'منڊي معيار',
        'fairFarmgateBand': 'مناسب ٻنيءَ جو اگهه',
        'hardFloorWarning': 'اڄ هن گهٽ ترين اگهه کان گهٽ تي نه وڪڻو',
        'shareWhatsApp': 'واٽس ايپ تي اگهه ڪارڊ موڪليو',
        'aggregatedSelling': 'گڏيل وڪرو (پول)',
        'popUpPoolTitle': 'پاپ اپ پول ۽ سڌا خريدار',
        'bulkBonus': 'گهڻي مال جو بونس',
        'poolProgress': 'پول ترقي',
        'joinPoolBtn': 'پول ۾ شامل ٿيو',
        'verifiedBuyers': 'تصديق ٿيل خريدار',
        'acceptOfferBtn': 'آفر قبول ڪري تور بڪ ڪريو',
        'quickEntry': 'جلدي داخلا',
        'speakToEnter': 'ڳالهائي فصل درج ڪريو',
        'recentDispatch': 'تازو مال روانو',
        'dbtSettled': 'بئنڪ کاتي ۾ جمع (DBT)',
        'disclaimerTitle': 'منڊي مِتر فيصلو سپورٽ سسٽم',
        'disclaimerText': 'هي سفارشون سرڪاري ايگمٽ ۽ موسم جي اڳڪٿي تي ٻڌل آهن.',
        'navHome': 'گهر',
        'navDecision': 'فيصلو',
        'navMarkets': 'منڊيون',
        'navBuyers': 'خريدار',
        'navLedger': 'حساب',
        'holdAction': 'ترسو',
        'sellNowAction': 'هاڻي وڪرو ڪريو',
        'joinPoolAction': 'پول ۾ شامل ٿيو',
        'factorPriceTrend': 'قيمت جو لاڙو',
        'factorWeather': 'موسم جي اڳڪٿي',
        'factorStorage': 'گودام جي سهولت',
        'factorSpoilage': 'خراب ٿيڻ جو خطرو',
        'modifyLot': 'فصل تفصيل تبديل ڪريو',
        'digitalLedger': 'هاري ڊيجيٽل کاتو',
        'directSettlements': 'سڌو بئنڪ ۾ ادائيگي',
        'totalRealized': 'ڪل مليل روڪ رقم',
        'settledVolume': 'وڪرو ٿيل مقدار',
        'settledInvoices': 'ادا ڪيل بل',
        'recordNewSale': 'نئون وڪرو درج ڪريو'
    },
    'doi': {
        'appName': 'मंडीमित्र',
        'subtitle': 'मंडी निर्णय केंद्र',
        'judgeDemo': 'जज डेमो',
        'easyMode': 'सरल मोड',
        'simulate': 'सिम्युलेट',
        'offline': 'ऑफलाइन',
        'onlineStatus': 'ऑनलाइन (सवेरे ७:३० सिंक)',
        'offlineStatus': 'ऑफलाइन (बचाया डेटा)',
        'sihEvaluation': 'SIH मूल्यांकन मोड',
        'testScenarios': 'किसान परिस्थितियां परखो:',
        'scenario1': 'रुको (प्याज)',
        'scenario2': 'हुन बेचो (टमाटार)',
        'scenario3': 'पॉप-अप पूल',
        'greeting': 'नमस्ते, रामेश्वर जी 👋',
        'location': 'रामेश्वर जी • निफाड, नासिक (महाराष्ट्र)',
        'geoVerified': 'स्थान सत्यापित',
        'onFarmStorage': 'खेत च भंडारण',
        'todaysMandi': 'अज्ज दा स्थानीय मंडी भाव',
        'sellingDecision': 'तुंदा बेचने दा फैसला',
        'confidence': 'विश्वास स्तर',
        'sellTodayNet': 'अज्ज बेचियै शुद्ध नकद',
        'spotPrice': 'नकद भाव',
        'mathDifferenceGain': 'अतिरिक्त मुनाफा',
        'whyThis': 'ए फैसला कीं? (कारण)',
        'compareMandis': 'मंडियां दी तुलना करो',
        'whatIfTitle': 'रुकी गे ता केह् होग? (सिम्युलेटर)',
        'whatIfSubtitle': 'दहाड़े दे हिसाब कन्ने अपनी असल कमाई दिक्खो',
        'testVariables': 'हालात बदली के दिक्खो:',
        'storageToggle': 'भंडारण',
        'rainToggle': 'बर्खा दी चेतावनी',
        'cashToggle': 'पैसे दी लोड़',
        'decisionFormulaTitle': 'फैसला समझदारी ते गणितीय सूत्र',
        'decisionFormulaSubtitle': 'SIH एल्गोरिदम तफ्सील',
        'whereToSell': 'कुत्थे बेचना? (बढ़िया मंडी)',
        'bestNetRealization': 'हत्थे च औने आला सर्वश्रेष्ठ शुद्ध मुनाफा',
        'headlineWarning': '⚠️ वड्डे भाव दिक्खियै धोखा नी खाओ। भाड़ा कड्डीयै शुद्ध बचत दिक्खो।',
        'leverageTitle': 'सौदाबाजी ताकत (लीवरेज)',
        'leverageSubtitle': 'व्यापारियें कन्नै गल्ल करने शा पैह्ले अपना न्यूनतम भाव जानो',
        'mandiBenchmark': 'मंडी मानक',
        'fairFarmgateBand': 'उचित खेत भाव दायरा',
        'hardFloorWarning': 'अज्ज इस न्यूनतम भाव शा घट्ट कदे नी बेचो',
        'shareWhatsApp': 'व्हाट्सएप पर भाव कार्ड भेजो',
        'aggregatedSelling': 'कट्ठा बेचना (पूल)',
        'popUpPoolTitle': 'पॉप-अप पूल ते सीधा खरीदार',
        'bulkBonus': 'थोक बोनस',
        'poolProgress': 'पूल प्रगति',
        'joinPoolBtn': 'पूल च शामल ओओ',
        'verifiedBuyers': 'प्रमाणित सीधा खरीदार',
        'acceptOfferBtn': 'प्रस्ताव मन्नी के तौल बुक करो',
        'quickEntry': 'झटपट प्रविष्टि',
        'speakToEnter': 'बोली के फसल दर्ज करो',
        'recentDispatch': 'पिशली भुगतानी',
        'dbtSettled': 'खाते च जमा (DBT)',
        'disclaimerTitle': 'मंडीमित्र फैसला सहायता प्रणाली',
        'disclaimerText': 'सिफारिशें सरकारी एगमार्कनेट ते मौसम पूर्वानुमान पर आधारित न।',
        'navHome': 'घर',
        'navDecision': 'फैसला',
        'navMarkets': 'मंडी',
        'navBuyers': 'खरीदार',
        'navLedger': 'खाता',
        'holdAction': 'रुको',
        'sellNowAction': 'हुन बेचो',
        'joinPoolAction': 'पूल च शामल ओओ',
        'factorPriceTrend': 'भाव दा रुझान',
        'factorWeather': 'मौसम दा पूर्वानुमान',
        'factorStorage': 'भंडारण क्षमता',
        'factorSpoilage': 'खराब होने दा खतरा',
        'modifyLot': 'फसल विवरण बदलो',
        'digitalLedger': 'किसान डिजिटल बहीखाता',
        'directSettlements': 'सीधे बैंक खाते च जमा',
        'totalRealized': 'कुल मिले दा नकद',
        'settledVolume': 'बेची दी मात्रा',
        'settledInvoices': 'भुगताने दे बिल',
        'recordNewSale': 'नमीं बिक्री दर्ज करो'
    },
    'brx': {
        'appName': 'मन्दामित्र',
        'subtitle': 'मन्दा थिरांथा मिरु',
        'judgeDemo': 'बिजिरग्रा दिन्थिथि',
        'easyMode': 'गोरलै रोखोम',
        'simulate': 'सिम्युलेट',
        'offline': 'अफलाइन',
        'onlineStatus': 'अनलाइन (फुंनि ७:३० सिंक)',
        'offlineStatus': 'अफलाइन (सावथुन डेटा)',
        'sihEvaluation': 'SIH बिजिरनाय रोखोम',
        'testScenarios': 'आबादारीनि थासारि नाय:',
        'scenario1': 'नेना था (पियाज)',
        'scenario2': 'दासानो फान (थामाथिर)',
        'scenario3': 'पप-आप पुल',
        'greeting': 'मोजां फुं, रामेश्वर बिदा 👋',
        'location': 'रामेश्वर बिदा • निफाड, नासिक (महाराष्ट्र)',
        'geoVerified': 'जायगा रोखा खालामनाय',
        'onFarmStorage': 'हाथाय दोन्थुमग्रा',
        'todaysMandi': 'दिनैनि हाथाय बेसेन',
        'sellingDecision': 'नोंथांनि फाननायनि थि खालामनाय',
        'confidence': 'फोथायथि',
        'sellTodayNet': 'दिनै फानब्ला मोननाय रोखा रां',
        'spotPrice': 'दाखालिनि बेसेन',
        'mathDifferenceGain': 'बांद्राय लाब',
        'whyThis': 'मानो बे थि खालामनाय? (जाहोन)',
        'compareMandis': 'हाथाय रुजुनाय',
        'whatIfTitle': 'नेना थानोब्ला मा जागोन? (सिम्युलेटर)',
        'whatIfSubtitle': 'साननि फारियै नोंथांनि थार लाब नाय',
        'testVariables': 'थासारिफोरखौ सोलायना नाय:',
        'storageToggle': 'दोन्थुमग्रा',
        'rainToggle': 'अखा हुसिराथि',
        'cashToggle': 'रांनि गोनांथि',
        'decisionFormulaTitle': 'थि खालामनाय गोरोनथि आरो सानखान्थि',
        'decisionFormulaSubtitle': 'SIH अल्गोरिदम बिथोन',
        'whereToSell': 'बहा फानगोन? (मोजांथार हाथाय)',
        'bestNetRealization': 'आवथायाव मोननाय मोजांथार रोखा लाब',
        'headlineWarning': '⚠️ गोजौ बेसेन नायनानै नंखाय जायनो नाङा। रोगानाय खरसाखौ दानखनानै लाबखौ नाय।',
        'leverageTitle': 'बेसेन सावरायनाय गोहो (लीवरेज)',
        'leverageSubtitle': 'फालांगिरिजों रायज्लायनायनि सिगां नोंथांनि खमसिन बेसेन मिथिखा',
        'mandiBenchmark': 'हाथाय मान',
        'fairFarmgateBand': 'थार आबाद बेसेन सिमा',
        'hardFloorWarning': 'दिनै बे खमसिन बेसेननि गाहायाव दा फान',
        'shareWhatsApp': 'हवाट्सआपआव बेसेन कार्ड हर',
        'aggregatedSelling': 'जौमै फाननाय (पुल)',
        'popUpPoolTitle': 'पप-आप पुल आरो थोंजों बायग्रा',
        'bulkBonus': 'गोबां फाननायनि बोनस',
        'poolProgress': 'पुलनि जौगानाय',
        'joinPoolBtn': 'पुलाव बाहागो ला',
        'verifiedBuyers': 'रोखा थोंजों बायग्रा',
        'acceptOfferBtn': 'प्रस्ताव गोरोबनानै ओजन बुक खालाम',
        'quickEntry': 'गोख्रै सोसननाय',
        'speakToEnter': 'बुंनानै फसल सोसन',
        'recentDispatch': 'दावहा सोलिनाय रां',
        'dbtSettled': 'बैंक खातायाव जमा (DBT)',
        'disclaimerTitle': 'मन्दामित्र थि खालामनाय हेफाजाब राहा',
        'disclaimerText': 'बे बिथोनफोरा सरकारि एगमार्कनेट आरो बथोर रादाबाव सोनारनाय।',
        'navHome': 'न\'',
        'navDecision': 'थि खालामनाय',
        'navMarkets': 'हाथाय',
        'navBuyers': 'बायग्राफोर',
        'navLedger': 'हिसाब',
        'holdAction': 'नेना था',
        'sellNowAction': 'दासानो फान',
        'joinPoolAction': 'पुलाव बाहागो ला',
        'factorPriceTrend': 'बेसेननि थासारि',
        'factorWeather': 'बथोरनि रादाब',
        'factorStorage': 'दोनथुमग्रा सुबिदा',
        'factorSpoilage': 'गाज्रि जानायनि खैफोद',
        'modifyLot': 'फसलनि विवरण सोलाय',
        'digitalLedger': 'आबादारी डिजिटल हिसाब',
        'directSettlements': 'थोंजों बैंक एकाउन्टआव जमा',
        'totalRealized': 'गासै मोननाय रां',
        'settledVolume': 'फाननाय बिबां',
        'settledInvoices': 'रां सुफुंनाय बिल',
        'recordNewSale': 'गोदान फाननाय सोसन'
    },
    'mni': {
        'appName': 'মেন্দীমিত্রা',
        'subtitle': 'মেন্দী ফিরেপ কেন্দ্র',
        'judgeDemo': 'বিচারক দেমো',
        'easyMode': 'চম্বা মোদ',
        'simulate': 'অনুকরণ',
        'offline': 'অফলাইন',
        'onlineStatus': 'অনলাইন (অয়ুক্কী ৭:৩০ সিঙ্ক)',
        'offlineStatus': 'অফলাইন (সেভ তৌরবা দেতা)',
        'sihEvaluation': 'SIH ইভালুৱেসন মোদ',
        'testScenarios': 'লৌমীশিংগী ফিভম য়েংউ:',
        'scenario1': 'ঙাইহাক লৈরো (তিলহৌ)',
        'scenario2': 'হৌজিক য়োল্লু (খোমনাম তিলহৌ)',
        'scenario3': 'পোপ-অপ পুল',
        'greeting': 'খুরুমজরি, রামেশ্বর দা 👋',
        'location': 'রামেশ্বর দা • নিফাদ, নাসিক (মহারাষ্ট্র)',
        'geoVerified': 'মফম চাং য়েংশিনবা',
        'onFarmStorage': 'লৌবুক্কী গুদাম',
        'todaysMandi': 'ঙসিসিগী মফমগী কৈথেল মমল',
        'sellingDecision': 'নহাক্কী য়োনবগী ৱারেপ',
        'confidence': 'থাজবা',
        'sellTodayNet': 'ঙসি য়োল্লবদি খুৎতা লৈহৌগদবা শেল',
        'spotPrice': 'নকপগী মমল',
        'mathDifferenceGain': 'অহেনবা কান্নবা',
        'whyThis': 'করীগীদমকসি ৱারেপনি? (মরমশিং)',
        'compareMandis': 'কৈথেলশিং চাংদম্নবা',
        'whatIfTitle': 'ঙাইরবদি করি থোক্কনি? (সিমুলেটর)',
        'whatIfSubtitle': 'নুমিৎ কয়ানিগী মতুংদা নহাক্কী অশেংবা ইনকম য়েংউ',
        'testVariables': 'ফিভমশিং হোংদোক্তুনা য়েংউ:',
        'storageToggle': 'গুদাম',
        'rainToggle': 'নোংগী চেকশিনৱা',
        'cashToggle': 'শেলগী তঙাইফদবা',
        'decisionFormulaTitle': 'ৱারেপ অমসুং মেথমেতিকেল ফোর্মুলা',
        'decisionFormulaSubtitle': 'SIH অলগোরিদম শন্দোক্না',
        'whereToSell': 'কদায়দা য়োনগনি? (খ্বাইদগী ফবা কৈথেল)',
        'bestNetRealization': 'খুৎতা য়াওগদবা খ্বাইদগী ফবা কান্নবা',
        'headlineWarning': '⚠️ ৱাংবা মমল উবদা নামথাহনগনু। পুথোক-পুশিনগী খর্চা লৌথোক্তুনা অহেনবা কান্নবা য়েংউ।',
        'leverageTitle': 'মমল খন্নবগী পাঙ্গল (লীবরেজ)',
        'leverageSubtitle': 'ললোনবাশিংগা ৱারী শানদ্রিঙৈদা নহাক্কী খ্বাইদগী হন্থবা মমল খঙউ',
        'mandiBenchmark': 'কৈথেলগী মানদন্দ',
        'fairFarmgateBand': 'চুম্বা লৌবুক্কী মমল',
        'hardFloorWarning': 'ঙসি মসিদগী হন্থবা মমলদা কৈদৌনুংদা য়োন্নাগনু',
        'shareWhatsApp': 'ৱাত্সঅপতা মমল কার্দ থারকউ',
        'aggregatedSelling': 'পুল্লোপ য়োনবা (পুল)',
        'popUpPoolTitle': 'পোপ-অপ পুল অমসুং হকথেংনবা লৈবা',
        'bulkBonus': 'য়াম্না য়োনবগী বোনস',
        'poolProgress': 'পুল চাউখৎপা',
        'joinPoolBtn': 'পুলদা য়াওরো',
        'verifiedBuyers': 'চাং য়েংশিল্লবা লৈরিবশিং',
        'acceptOfferBtn': 'ওফর য়াবিয়ু অমসুং ওনবা বুক তৌরো',
        'quickEntry': 'থুনা ইচংবা',
        'speakToEnter': 'ৱা ঙাংদুনা পোত্থোক চংহনবা',
        'recentDispatch': 'হন্দক্কী থাদোকখিবা',
        'dbtSettled': 'বেঙ্ক একাউন্ততা হাপচিল্লে (DBT)',
        'disclaimerTitle': 'মেন্দীমিত্রা ৱারেপ শৌগৎপা সিস্তেম',
        'disclaimerText': 'সিফারিশশিং অসি সর্কারগী অগমর্কনেৎ অমসুং নুংশিৎ-ঈশিংগী পাউদা য়ুমফম ওল্লি।',
        'navHome': 'য়ুম',
        'navDecision': 'ৱারেপ',
        'navMarkets': 'কৈথেল',
        'navBuyers': 'লৈরিবশিং',
        'navLedger': 'হিসাব',
        'holdAction': 'ঙাইহাক লৈরো',
        'sellNowAction': 'হৌজিক য়োল্লু',
        'joinPoolAction': 'পুলদা য়াওরো',
        'factorPriceTrend': 'মমলগী চৎনবী',
        'factorWeather': 'নুংশিৎ-ঈশিংগী পাউ',
        'factorStorage': 'থমহনবগী শক্তি',
        'factorSpoilage': 'মাং-তাকপগী খুদোংথিবা',
        'modifyLot': 'পোত্থোক্কী অকুপ্পা হোংদোকউ',
        'digitalLedger': 'লৌমী দিজিতেল হিসাব',
        'directSettlements': 'হকথেংননা বেঙ্ক একাউন্ততা পীবীবা',
        'totalRealized': 'অপুনবা ফংলবা শেল',
        'settledVolume': 'য়োঙ্খ্রবা অপুনবা',
        'settledInvoices': 'শেল পীখ্রবা বিলশিং',
        'recordNewSale': 'অনৌবা য়োনবা ইরো'
    },
    'sat': {
        'appName': 'ᱢᱟᱱᱰᱤᱢᱤᱛᱨᱚ',
        'subtitle': 'ᱦᱟᱴ ᱯᱷᱟᱹᱭᱥᱟᱞᱟ ᱛᱟᱞᱢᱟ',
        'judgeDemo': 'ᱡᱚᱡᱽ ᱰᱮᱢᱳ',
        'easyMode': 'ᱟᱞᱜᱟ ꯃᱳᱰ',
        'simulate': 'ᱥᱤᱢᱩᱞᱮᱴ',
        'offline': 'ᱚᱯᱷᱞᱟᱭᱤᱱ',
        'onlineStatus': 'ᱚᱱᱞᱟᱭᱤᱱ (ᱥᱮᱛᱟᱜ ᱗:᱓᱐)',
        'offlineStatus': 'ᱚᱯᱷᱞᱟᱭᱤᱱ (ᱥᱟᱺᱪᱟᱣ ᱰᱮᱴᱟ)',
        'sihEvaluation': 'SIH ᱢᱩᱞᱭᱟᱸᱠᱚᱱ ꯃᱳᱰ',
        'testScenarios': 'ᱪᱟᱹᱥᱤ ᱦᱟᱞᱚᱛ ᱧᱮᱞ ᱢᱮ:',
        'scenario1': 'ᱛᱟᱺᱜᱤᱭ ᱢᱮ (ᱯᱮᱭᱟᱸᱡᱽ)',
        'scenario2': 'ᱱᱤᱛ ᱜᱮ ᱟᱹᱠᱷᱨᱤᱧ ᱢᱮ (ᱵᱤᱞᱟᱹᱛᱤ)',
        'scenario3': 'ᱯᱚᱯ-ᱟᱯ ᱯᱩᱞ',
        'greeting': 'ᱡᱚᱦᱟᱨ, ᱨᱟᱢᱮᱥᱣᱚᱨ ᱜᱚᱝᱠᱮ 👋',
        'location': 'ᱨᱟᱢᱮᱥᱣᱚᱨ ᱜᱚᱝᱠᱮ • ᱱᱤᱯᱷᱟᱰ, ᱱᱟᱥᱤᱠ (ᱢᱚᱦᱟᱨᱟᱥᱴᱨᱚ)',
        'geoVerified': 'ᱴᱷᱟᱶ ᱯᱚᱨᱢᱟᱱ',
        'onFarmStorage': 'ᱵᱟᱹᱫᱽ ᱨᱮ ᱫᱚᱦᱚ ᱴᱷᱟᱶ',
        'todaysMandi': 'ᱛᱮᱦᱮᱧᱟᱜ ᱦᱟᱴ ᱫᱟᱢ',
        'sellingDecision': 'ᱟᱢᱟᱜ ᱟᱹᱠᱷᱨᱤᱧ ᱯᱷᱟᱹᱭᱥᱟᱞᱟ',
        'confidence': 'ᱯᱟᱹᱛᱭᱟᱹᱣ',
        'sellTodayNet': 'ᱛᱮᱦᱮᱧ ᱟᱹᱠᱷᱨᱤᱧ ᱞᱮᱠᱷᱟᱱ ᱛᱤ ᱨᱮ ᱦᱤᱡᱩᱜ ᱠᱟᱹᱣᱰᱤ',
        'spotPrice': 'ᱱᱤᱛᱚᱜᱟᱜ ᱫᱟᱢ',
        'mathDifferenceGain': 'ᱵᱟᱹᱲᱛᱤ ᱞᱟᱵᱷ',
        'whyThis': 'ᱪᱮᱫᱟᱜ ᱱᱚᱶᱟ ᱯᱷᱟᱹᱭᱥᱟᱞᱟ? (ᱠᱟᱨᱚᱱ)',
        'compareMandis': 'ᱦᱟᱴ ᱠᱚ ᱛᱩᱞᱟᱹᱡᱚᱠᱷᱟ',
        'whatIfTitle': 'ᱛᱟᱺᱜᱤ ᱞᱮᱠᱷᱟᱱ ᱪᱮᱫ ᱦᱩᱭᱩᱜ-ᱟ? (ᱥᱤᱢᱩᱞᱮᱴᱚᱨ)',
        'whatIfSubtitle': 'ᱢᱟᱦᱟᱸ ᱞᱮᱠᱟᱛᱮ ᱟᱢᱟᱜ ᱟᱹᱥᱚᱞ ᱟᱨᱡᱟᱣ ᱧᱮᱞ ᱢᱮ',
        'testVariables': 'ᱦᱟᱞᱚᱛ ᱵᱚᱫᱚᱞ ᱠᱟᱛᱮ ᱧᱮᱞ ᱢᱮ:',
        'storageToggle': 'ᱫᱚᱦᱚ ᱴᱷᱟᱶ',
        'rainToggle': 'ᱫᱟᱜ ᱦᱩᱰᱩᱨ ᱦᱚᱸᱥᱤᱭᱟᱨ',
        'cashToggle': 'ᱠᱟᱹᱣᱰᱤ ᱞᱟᱹᱠᱛᱤ',
        'decisionFormulaTitle': 'ᱯᱷᱟᱹᱭᱥᱟᱞᱟ ᱫᱤᱥᱟᱹ ᱟᱨ ᱞᱮᱠᱷᱟ ᱥᱩᱛᱩᱨ',
        'decisionFormulaSubtitle': 'SIH ᱮᱞᱜᱳᱨᱤᱫᱚᱢ ᱵᱤᱵᱚᱨᱚᱬ',
        'whereToSell': 'ᱚᱠᱟᱨᱮ ᱟᱹᱠᱷᱨᱤᱧᱟ? (ᱵᱷᱟᱹᱜᱤ ᱦᱟᱴ)',
        'bestNetRealization': 'ᱛᱤ ᱨᱮ ᱧᱟᱢᱚᱜ ᱥᱚᱨᱮᱥ ᱠᱷᱟᱸᱴᱤ ᱞᱟᱵᱷ',
        'headlineWarning': '⚠️ ᱩᱥᱩᱞ ᱫᱟᱢ ᱧᱮᱞᱛᱮ ᱟᱞᱚᱢ ᱵᱷᱩᱞᱟᱹᱜ-ᱟ᱾ ᱜᱟᱹᱰᱤ ᱵᱷᱟᱲᱟ ᱵᱟᱫᱽ ᱠᱟᱛᱮ ᱛᱤ ᱨᱮᱭᱟᱜ ᱧᱮᱞ ᱢᱮ᱾',
        'leverageTitle': 'ᱫᱟᱢ ᱢᱚᱱᱮ ᱫᱟᱲᱮ (ᱞᱤᱵᱷᱨᱮᱡᱽ)',
        'leverageSubtitle': 'ᱵᱮᱯᱟᱨᱤ ᱥᱟᱶ ᱨᱚᱯᱚᱲ ᱢᱟᱲᱟᱝ ᱟᱢᱟᱜ ᱠᱚᱢ ᱫᱟᱢ ᱵᱟᱰᱟᱭ ᱢᱮ',
        'mandiBenchmark': 'ᱦᱟᱴ ᱢᱟᱱᱚᱠ',
        'fairFarmgateBand': 'ᱥᱚᱦᱚᱡᱽ ᱵᱟᱹᱫᱽ ᱫᱟᱢ ᱥᱤᱢᱟᱹ',
        'hardFloorWarning': 'ᱛᱮᱦᱮᱧ ᱱᱚᱶᱟ ᱠᱚᱢ ᱫᱟᱢ ᱠᱷᱚᱱ ᱞᱟᱛᱟᱨ ᱨᱮ ᱟᱞᱚᱢ ᱟᱹᱠᱷᱨᱤᱧᱟ',
        'shareWhatsApp': 'ᱣᱟᱴᱥᱮᱯ ᱨᱮ ᱫᱟᱢ ᱠᱟᱨᱰ ᱵᱷᱮᱡᱟᱭ ᱢᱮ',
        'aggregatedSelling': 'ᱡᱚᱛᱚ ᱢᱮᱥᱟ ᱟᱹᱠᱷᱨᱤᱧ (ᱯᱩᱞ)',
        'popUpPoolTitle': 'ᱯᱚᱯ-ᱟᱯ ᱯᱩᱞ ᱟᱨ ᱥᱚᱡᱷᱮ ᱠᱤᱨᱤᱧᱤᱭᱟᱹ',
        'bulkBonus': 'ᱵᱟᱹᱲᱛᱤ ᱢᱟᱞ ᱵᱳᱱᱟᱥ',
        'poolProgress': 'ᱯᱩᱞ ᱞᱟᱦᱟᱱᱛᱤ',
        'joinPoolBtn': 'ᱯᱩᱞ ᱨᱮ ᱥᱮᱞᱮᱫᱚᱜ ᱢᱮ',
        'verifiedBuyers': 'ᱯᱚᱨᱢᱟᱱ ᱥᱚᱡᱷᱮ ᱠᱤᱨᱤᱧᱤᱭᱟᱹ',
        'acceptOfferBtn': 'ᱚᱯᱷᱟᱨ ᱦᱟᱛᱟᱣ ᱢᱮ ᱟᱨ ᱛᱩᱞᱟᱹ ᱵᱩᱠ ᱢᱮ',
        'quickEntry': 'ᱞᱚᱜᱚᱱ ᱮᱱᱴᱨᱤ',
        'speakToEnter': 'ᱨᱚᱲ ᱠᱟᱛᱮ ᱯᱷᱚᱥᱚᱞ ᱚᱞ ᱢᱮ',
        'recentDispatch': 'ᱱᱤᱛᱚᱜᱟᱜ ᱠᱟᱹᱣᱰᱤ ᱡᱚᱢᱟ',
        'dbtSettled': 'ᱵᱮᱸᱠ ᱠᱷᱟᱛᱟ ᱨᱮ ᱡᱚᱢᱟ (DBT)',
        'disclaimerTitle': 'ᱢᱟᱱᱰᱤᱢᱤᱛᱨᱚ ᱯᱷᱟᱹᱭᱥᱟᱞᱟ ᱜᱚᱲᱚ ᱵᱮᱵᱚᱥᱛᱷᱟ',
        'disclaimerText': 'ᱱᱚᱶᱟ ᱠᱚᱫᱚ ᱥᱚᱨᱠᱟᱨᱤ ᱮᱜᱽᱢᱟᱨᱠᱱᱮᱴ ᱟᱨ ᱦᱚᱭ-ᱦᱤᱥᱤᱫ ᱞᱟᱦᱟ ᱵᱟᱰᱟᱭ ᱪᱮᱛᱟᱱ ᱨᱮ ᱴᱮᱦᱟᱸᱰ ᱟᱠᱟᱱᱟ᱾',
        'navHome': 'ᱚᱲᱟᱜ',
        'navDecision': 'ᱯᱷᱟᱹᱭᱥᱟᱞᱟ',
        'navMarkets': 'ᱦᱟᱴ',
        'navBuyers': 'ᱠᱤᱨᱤᱧᱤᱭᱟᱹ',
        'navLedger': 'ᱠᱷᱟᱛᱟ',
        'holdAction': 'ᱛᱟᱺᱜᱤᱭ ᱢᱮ',
        'sellNowAction': 'ᱱᱤᱛ ᱜᱮ ᱟᱹᱠᱷᱨᱤᱧ ᱢᱮ',
        'joinPoolAction': 'ᱯᱩᱞ ᱨᱮ ᱥᱮᱞᱮᱫᱚᱜ ᱢᱮ',
        'factorPriceTrend': 'ᱫᱟᱢ ᱨᱮᱱᱟᱜ ᱪᱟᱞᱟᱣ',
        'factorWeather': 'ᱦᱚᱭ-ᱦᱤᱥᱤᱫ ᱞᱟᱦᱟ ᱵᱟᱰᱟᱭ',
        'factorStorage': 'ᱫᱚᱦᱚ ᱫᱟᱲᱮ',
        'factorSpoilage': 'ᱵᱟᱹᱲᱤᱡᱚᱜ ᱨᱮᱱᱟᱜ ᱵᱚᱛᱚᱨ',
        'modifyLot': 'ᱯᱷᱚᱥᱚᱞ ᱵᱤᱵᱚᱨᱚᱬ ᱵᱚᱫᱚᱞ ᱢᱮ',
        'digitalLedger': 'ᱪᱟᱹᱥᱤ ᱰᱤᱡᱤᱴᱟᱞ ᱠᱷᱟᱛᱟ',
        'directSettlements': 'ᱥᱚᱡᱷᱮ ᱵᱮᱸᱠ ᱠᱷᱟᱛᱟ ᱨᱮ ᱡᱚᱢᱟ',
        'totalRealized': 'ᱡᱚᱛᱚ ᱧᱟᱢ ᱟᱠᱟᱱ ᱠᱟᱹᱣᱰᱤ',
        'settledVolume': 'ᱟᱹᱠᱷᱨᱤᱧ ᱟᱠᱟᱱ ᱯᱚᱨᱤᱢᱟᱱ',
        'settledInvoices': 'ᱯᱩᱨᱟᱹᱣ ᱟᱠᱟᱱ ᱵᱤᱞ',
        'recordNewSale': 'ᱱᱟᱶᱟ ᱟᱹᱠᱷᱨᱤᱧ ᱚᱞ ᱢᱮ'
    }
}

print("Nine languages defined successfully.")
